#!/bin/bash

./importLibs 

makenek Nek_SSRM || { 
    echo "Error compiling..." 
    exit 1
}

genmap <<< 'channel_2D


' || { 
    echo "Error creating map file..." 
    exit 1
}


./runArnoldi channel_2D 2 0 10 
