#!/bin/bash

cmd="ln -s "

$cmd ../../Libs/FFT/FFT.f .
$cmd ../../Libs/FFT/FFT_DEF .
$cmd ../../Libs/FIR/FIR.f .
$cmd ../../Libs/FLD2Force/FLD2Force.f .
$cmd ../../Libs/FLD2Force/FLD2Force_DEF .
$cmd ../../Libs/Load_FLD/Load_FLD_To.f .
$cmd ../../Libs/Shapes/Shapes_DEF .
$cmd ../../Libs/Shapes/Shapes.f .
$cmd ../../Libs/SavePerturbations/SavePerturbations.f .
