#!/bin/bash

./importLibs 

makenek Nek_TRM || { 
    echo "Error compiling..." 
    exit 1
}

genmap <<< 'channel_2D


' || { 
    echo "Error creating map file..." 
    exit 1
}


./run channel_2D 2 0 10 y
